# Generated by Django 4.2.5 on 2023-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
    ]
