# Generated by Django 4.2.5 on 2023-09-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurantmenu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='cuisson_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='for_people',
            field=models.IntegerField(default=4),
        ),
    ]
