# Generated by Django 4.2.5 on 2023-09-14 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurantmenu_cuisson_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantmenu',
            options={'ordering': ('creation_date',)},
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
