# Generated by Django 4.2.5 on 2023-09-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_rename_order_orderrestaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenu',
            name='price',
            field=models.IntegerField(),
        ),
    ]
