# Generated by Django 4.2.5 on 2023-09-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_restaurantmenu_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantmenu',
            options={'ordering': ('creation_date',)},
        ),
        migrations.RemoveField(
            model_name='orderrestaurant',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='orderrestaurant',
            name='delivery',
            field=models.BooleanField(default=True),
        ),
    ]
